//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVUserRoleOrg.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_Vw
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string Orgname { get; set; }
        public string rolename { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
